
spring:
  application:
    name: API-GATEWAY
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-services
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees/(?<path>.*), /$\{path}
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - RewritePath=/departments/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: employees
        url: /v3/api-docs/employees
      - name: departments
        url: /v3/api-docs/departments
